### ISSUE TITLE
Implement Divider Block

### ISSUE THREAD

**Issue by zusamarehan** [zusamarehan/laravel-notion-renderer#4]
### Introduction

To see this Laravel Package in action, visit: [Evaluate Blogs](https://getevaluate.app/blogs?ref=github-issue), the whole blogging system lives in Notion and renders in the web page using this package and styled using [TailwindCSS Typography](https://tailwindcss.com/docs/typography-plugin)

### Requirements 

To implement Notion's Divider block, more info here: https://developers.notion.com/reference/block#divider-blocks

### Tasks

- [ ] Request to be assigned to the task
- [ ] Get assigned to the task
- [ ] Implement Callout Block
- [ ] Test thoroughly 
- [ ] Add Screenshots/Video Recordings as POW

### Notes
Just use the same Block Skeleton used for other blocks if you are unable to grasp the current code base. Also, if you have any ideas to improve the Block's Skelton, feel free!

**Happy Coding**
